export const QUERY_KEYS = {
  ACCU_CONDOTIONS: ["ACCU", "CURRENT_CONDITIONS"],
  ACCU_FORECAST: ["ACCU", "FIVE_DAY_FORCAST"],
  ACCU_SEARCH: ["ACCU", "SEARCH"],
  GOOGLE_PLACE: ["GOOGLE", "PLACE"],
  GOOGLE_PHOTO: ["GOOGLE", "PHOTO"],
};
